### ISSUE TITLE
Could you provide a cygwin use case?

### ISSUE THREAD

**Issue by reckoner** [degyves/VimPyServer#1]
You mentioned earlier that there was a use-case for cygwin on Windows. Can you please develop that more in your documentation? I'm having some trouble understanding how that would work and what it would be used for.

Thanks!

**Comment by victor-degyves** [comment]
Sure. I'm going to rewrite it.

In fact, I have developed it because I like to have only one instance of Vim to edit everything on my computer. I hope the next rewrite will explain it better.

**Comment by victor-degyves** [comment]
I have just updated the repository, plugin and documentation. Hope now it will be simpler to use it. It would be nice if you can try it and comment it.
